apiVersion: v1
kind: Service
metadata:
  name: wallet-whatsapp-verify
  labels:
    app: wallet-whatsapp-verify
spec:
  selector:
    app: wallet-whatsapp-verify
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
